# This docker file will be used to start a mysql docker container for storing the raw data 
version: "3.9"

services:
  mysql-raw:
    image: mysql
    network_mode: "host"
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
    ports:
      - "3306:3306"
      - "33060:33060"
    volumes:
      - ./mysql_data:/var/lib/mysql
